### PR TITLE
Fixed multiple issues to make it work.

### PR DESCRIPTION
**Pull request by Ghostbird**
- makezip.sh relied on rather complex and specifix bash functionality.
- makezip.sh was called from install.sh using "sh", so on systems
  where sh is not bash, install failed.
- Replaced bash specific things with more generic shell commands.
- Several rm commands were trying to delete files that might not be there
  this would show apparent errors in the install output, even though
  nothing was wrong.
- Made the process of removing, creating and extracting the zip entirely
  quiet to the user (errors will be shown). The only reason for the construction
  seems to be that windows lacks a tool that allows one to copy but exclude
  files matching a certain pattern.

### CODE REVIEW

**Comment by Ghostwalker71** [comment]
Those bash specific commands must be in place to update the git index data for development and shouldn't effect the end users as they will be using the blender built in add-on utility to install the niftools add-on.

**Comment by neomonkeus** [comment]
Changes are fine to me.

You might want to look at https://github.com/niftools/buildenv. its a session dependency management script which helps avoid bloating your dev environment. We use it alot and some of the scripts assume that those setting are available. As we mainly dev on win, the *nix version was never developed any further than the basic stuff. Might be something that interests you, unless you just want to build the plugin only.

**Comment by Ghostbird** [comment]
I just wanted to install it as a user, but I had overlooked the installation instructions that said how you could do it from inside Blender.
Then I looked in the install directory and tried to run the scripts. I found out that they did not work, so I  fixed that.
I guess I'll try the install from Blender.

**Comment by neomonkeus** [comment]
Still the contribution is welcome none the less :D

**Pull request merged**
