### PR TITLE
Ngon fixes

### LINKED ISSUE #208: Link to PyFFI submodule seems dead.
I needed the submodule (obviously) however when I tried to get it:

```
blender_nif_plugin$ git submodule update --init --recursive
Cloning into 'pyffi'...
fatal: unable to connect to git.code.sf.net:
git.code.sf.net[0: 216.34.181.155]: errno=Connection refused

Clone of 'git://git.code.sf.net/p/pyffi/code' into submodule path 'pyffi' failed
```

### LINKED ISSUE #243: Assertion Error : f_numverts == 3 or 4
@niftools/blender-nif-plugin-reviewer 
## Issue Overview

Unable to export as there is an assertion on the number of vertices
### Blender Nif Plugin Version Info

Blender Nif Plugin v2.6.0.dev4-02-04-2016
https://www.dropbox.com/s/6r7gz3m38r83x6e/blender_nif_plugin-2.6.0a0.dev4-02.04.2016.zip?dl=0
### Blender Version Info

Blender 2.77 64bit - Default installation location
### Platform information

Win 7
## Context

Attempting to export the mesh fails with the supplied messages.
It appears that there is faces without the required number of vertices
## Steps to Reproduce

 #. Export the mesh with the default settings targeting Skyrim.
## Expected Result

Mesh should be exported without error
## Actual Result

Unable to export the mesh due to the assertion check
## Possible Fix
- Check that there the assertion is correct as the mesh appears to be triangulated
- Improvement to highlight the problematic face, should think about whether or not to process all and assert at the end instead to provide the most feedback
- Improvement to use triangulation modifier
## Screenshot

N/A
## Logs and Files

[Provide logs file generated during the error as well as the blend and nif files are related to the issue]
### Info Bar Output

Traceback (most recent call last):

```
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\operators\nif_export_op.py", line 171, in execute
    return nif_export.NifExport(self, context).execute()
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\nif_export.py", line 261, in execute
    self.objecthelper.export_node(root_object, 'localspace', root_block, root_object.name)
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\objectsys\object_export.py", line 214, in export_node
    self.mesh_helper.export_tri_shapes(b_obj, space, parent_block, node_name)
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\objectsys\object_export.py", line 929, in export_tri_shapes
    assert((f_numverts == 3) or (f_numverts == 4)) # debug
AssertionError

location: <unknown location>:-1
```
### Console Output

```
C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\ui\shader.py:113
Traceback (most recent call last):
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\operators\nif_export_op.py", line 171, in execute
    return nif_export.NifExport(self, context).execute()
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\nif_export.py", line 261, in execute
    self.objecthelper.export_node(root_object, 'localspace', root_block, root_object.name)
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\objectsys\object_export.py", line 214, in export_n
ode
    self.mesh_helper.export_tri_shapes(b_obj, space, parent_block, node_name)
  File "C:\Users\monkey\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\io_scene_nif\objectsys\object_export.py", line 929, in export_t
ri_shapes
    assert((f_numverts == 3) or (f_numverts == 4)) # debug
AssertionError

location: <unknown location>:-1

location: <unknown location>:-1
```
### Blend File

https://www.dropbox.com/s/whx77f196zjajiq/Daedric%20Steel%203.blend?dl=0
### Nif File

N/A
## Similar Known Issues

N/A
## Additional Information

N/A

### PR DESCRIPTION
**Pull request by psi29a**
@niftools/blender-nif-plugin-reviewer 

# Overview
Converts all quads and n-gons into triangles.
Also fixes up .gitignore and .gitmodules

## Fixes Known Issues
Closes #243
Closes #208 

## Documentation
None

## Testing
None; assert no longer triggers

### Manual
https://www.dropbox.com/s/6r7gz3m38r83x6e/blender_nif_plugin-2.6.0a0.dev4-02.04.2016.zip?dl=0
^-- try exporting this

### Automated
None; assert no longer triggers

## Additional Information
None

### CODE REVIEW

**Comment by nightstrike** [comment]
While I, too, hit this error, I think the spirit of the assertion is a good thing. In my case, I had a mistaken face with 46 vertices. This was the root of the problem, which I fixed. I wouldn't have known about it without the assertion.  I think a much better fix would be for the plugin to communicate back that it found a giant n-gon face, and highlight it or select it or something.

**Comment by neomonkeus** [comment]
What we really want to do is add a triangulate modifier to the mesh, so that the user doesn't even have to care. Not sure about the case of 1 or 2 verts hanging about the place.

**Comment by nightstrike** [comment]
But then the user wouldn't know about an obvious mistake, such as what I had. He'd be left with a much heavier mesh than necessary.

**Comment by neomonkeus** [comment]
There are two separate concerns here.
- Having a mesh that is exportable
-- Should be repeatable & non-destructive.
- Letting the use know early that the mesh has an n-gon.
In the latter case you might be "lucky" and have some n-gon which is not a multiple of 3, i.e in your case if it had been 45 verts, you would have been none the wiser.

**Pull request closed without merging**
