### PR TITLE
Pep8

### PR DESCRIPTION
**Pull request by Ghostwalker71**
This pull brings all modules into compliance with pep8 standards as well as finally getting rid of the mixed tabs and spaces issue.

### CODE REVIEW

**Comment by neomonkeus** [comment]
While I agree with some of the space tab vs tabs inconsistency, the 79 char length & resulting line wrapping in a lot of places makes it less readable.

**Comment by Ghostwalker71** [comment]
While I agree that in some places the folding has made the code less readable, I find that in most cases it became easier to read and at a glance you can see what data is being called by a line of code. if you have any specific lines that are a problem I can take another look at them and attempt to make them more clear.
Also if you no longer intend to submit the project to blender for inclusion you can choose to ignore the pep8 standards. It makes no difference to me which you chose. I would simply like to get the project moving forward.

**Comment by neomonkeus** [comment]
I went through just one file and marked alot of the unreadable - https://github.com/Ghostwalker71/blender_nif_plugin/commit/c02d9a5420ec4c2f0c4240f6a2f41edfb1c7d6ea . It definitely decreases readability in far too many areas.

Blender does not enforce pep8, plugin authors choose whether or not they want to be pep8 compliant. 

Making it less readible won't really help the project move forward.

**Comment by Ghostwalker71** [comment]
Well I read your "line notes" and I completely disagree with you on nearly every one, feel free to reject the pull.

**Comment by Ghostwalker71** [comment]
Well, I'm apparently still missing some points on how the conventions works, I'll just go back to doing my own thing. o7

**Comment by Brandano** [comment]
I didn't want to come through as adversarial, and sincerely I didn't want you to close this pull request outright without discussing it. I am sure you have good reasons for this pull request and I'd like to hear them.

**Comment by neomonkeus** [comment]
Likewise, this is why I asked @Brandano to contribute his opinion.

I do think that it does include things that do improve things, such as ensuring consistency with tabs, how the matrix construction mirrors how we would read it, where operators are placed, etc.

**Comment by Ghostwalker71** [comment]
@Brandano you didn't come across as adversarial, you made valid points.
I made the changes, in the manner I did, primarily to reach full compliance to the pep8 standard, which I thought was an overall end goal for submitting the project to blender for full inclusion. I figured it would be easier to get it there now while nothing else was being done. That way it would be easier to maintain the standard moving forward. Also I felt the changes improved readability rather than diminished it, obviously I was wrong on that point.
I closed the pull because the tedium of going back and trying to unfold all of those edited lines was worse than changing the settings in eclipse to exclude the line length limit and redo the other edits, but I don't have any real idea when I will manage to do that.
Conversely, if It is preferred that I reopen the commit and make the further edits to it, I can do that. Though I still do not have a full grasp on how the line length should be set and there is the tedium factor to consider.

**Pull request closed without merging**
