### PR TITLE
Contribution Document

### PR DESCRIPTION
**Pull request by neomonkeus**
@niftools/blender-nif-plugin-reviewer 

Adds general documentation for contributions.

### CODE REVIEW

**Comment by GandaG** [comment]
You can also place this one inside the .github folder.

**Comment by neomonkeus** [comment]
What advantage does that give?

**Comment by GandaG** [comment]
Less clutter at the repo's root? The same advantage that placing the others there gives.

**Comment by neomonkeus** [comment]
Well the .github folder would specifically be for github related stuff but generalising, yes a .hidden folder could be used to organise files but specifically for these files we want to keep them as glaringly visible as possible.

**Comment by GandaG** [comment]
Ok, that makes sense. A link could also be placed in the readme, no?

**Comment by neomonkeus** [comment]
Yeah, but I accidently included it in the wrong PR - https://github.com/niftools/blender_nif_plugin/pull/239/commits/4120138d756f7c3c4c137930c87956e2e7190872

**Pull request merged**
