### PR TITLE
Fix : TestFramework - Basic Integration tests working

### LINKED ISSUE #233: Export Context Polling Failure
When exporting, the following error is observed
image

### PR DESCRIPTION
**Pull request by neomonkeus**
@niftools/blender-plugin-reviewer 

Updated testframework to work again, with the minimum required feature set for object import/export.
This potentially breaks other tests cases and functionality, but that will be address by fixing each test case in turn and adding new tests. 

- Created object level test to test basic object transforms 
- Fixed several issues with transforms discovered from new tests, including scale & rotation.
- Reported #229 - Incorrect root name being set
- Removed unnecessary versioning code.
- Updated Documentation to reflect updates
- Fixes #233 - Export failure due to mode context polling issue

### CODE REVIEW

**Comment by Dexesttp** [comment]
This seems good, and I trust you tested the framework execution.

However, I have some questions about the relevancy of keeping the comments in `io_scene_nif/utility/nif_utils.py`, [here](https://github.com/neomonkeus/blender_nif_plugin/blob/fix/testframework_bsbound/io_scene_nif/utility/nif_utils.py#L77), lines 77 to 82 and below, lines 89 to 91. These comments seems to be a way to store old code while git should already handle that.

**Comment by neomonkeus** [comment]
Yep, being a lazy programmer, rather run the test framework than manually verifling test cases every update. If you mean are all test cases running, then no; Getting all the tests working is outside the scope of this PR, but the new test added shows tests can execute.  So we are improving the suite in this process and proves the test framework is functional again.

Yes, normally I would say to remove comments but I think we should keep it. I think the fix for transforms potentially brakes functionality (bones transforms) so will kept it until that code is verified that this code isn't needed anymore.

**Comment by Dexesttp** [comment]
Ok, so there is an extra comment line to be added then, just before the commented code.

To sum the problem up, the new implementation doesn't add scale to the transform data as it isn't needed for objects. Which is fine because the tests are now only made on objects.

However, in a future update tests would be added for e.g. armature which may need these scale in the transform data to pass. Therefore, the code that allows these scales to be added is commented, but not deleted.

**Comment by neomonkeus** [comment]
Actually no, the scale is being extracted for use by whatever need is.

I didn't see a purpose for the sqr(scale(x,y,z)), at least in its curent form as it wasn't returning a correct scale value. eg the test set the scale to 7.5 but the value being set was 0.85. sqr(0.75) == 0.85.

Having a look at the full original implementation it did additional operations, so if it is required then we should examine the algorithm as a whole.
See - https://github.com/niftools/blender_nif_plugin/blob/blender-2.5.9/scripts/export/export_nif.py#L3307 for original implementation

As far as I can tell the old code was extracting out the scale because of a limitation in the API that it couldn't read the sign.
> scalePart()
>  
> Return a the scale part of a 3x3 or 4x4 matrix.
> 
> Returns: Vector object.
> Return a the scale of a matrix.
> **Note: This method does not return negative a scale on any axis because it is not possible to obtain this data from the matrix alone.** 

For now, the test proves the current implementation work for positive scales. It might be a good idea to write an issue with a negative scale or what the rest was doing is the root.

**Comment by Dexesttp** [comment]
Ok, with the issue opened in #236, I validate the changes and merged.

**Pull request merged**
